# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: out
topnav_title: thirty bees developer documentation
homepage_title: thirty bees developer documentation
site_title: thirty bees developer documnatation
project_folder: mydoc
company_name: thirty bees
footer_image_location: ../common_images/company_logo.png
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname: idrbwjekyll
# variables

sidebar_tagline: Designers
sidebar_version: Version 4.0
theme_file: modern-business.css
pdf_file_name: mydoc_designers_pdf.pdf

gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'NZAMRQCZYF'
  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*
  - vendor

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

